### ISSUE TITLE
[Feature request] Non-flakes version

### ISSUE THREAD

**Issue by LoveIsGrief** [numtide/nixos-anywhere#190]
**Is your feature request related to a problem? Please describe.**

Not exactly a problem, but I'm one of those people waiting for flakes to become stable as it's an experimental feature and I don't quite understand what it does.Reading a normal nix file is easier for me to understand and figure out what's going on, which seems kind of important before installing an OS.  
Not sure how the split it in the nix community between flakes users and non-flakes users, but if it's 50/50 then about 50% of the nix community can't use nixos-anywhere.

**Describe the solution you'd like**

Not entirely sure if it fits but something like [flake-compat](https://github.com/edolstra/flake-compat) for the project and instructions how to use non-flakes?

**Describe alternatives you've considered**

Waiting until flakes is stable.

**Additional context**

**Comment by Lassulus** [comment]
ah nixos-anywhere runs without flakes. you can just pass the disko and nixos store paths with --store-paths /nix/store/yadayada-mydiskoscript /nix/store/wololo-mynixostoplevel. Documenting this is not feasible since without flakes there are a million ways to generate those paths.

for running nixos-anywhere, you can either execute the script directly in src/nixos-anywhere.sh or use the default.nix in there to get a wrapper with all the dependencies.

**Comment by Mic92** [comment]
https://github.com/numtide/nixos-anywhere/pull/194
